spring:
  application:
    name: bookservice
  datasource:
    url: jdbc:h2:mem:bookdb
    username: sa
    password: password # Có thể bỏ để quá trình login nhanh hơn
    driverClassName: org.h2.Driver # http://localhost:9001/h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # create: khi khởi động lại service hibernate sẽ tiến hành tạo lại schema table trong CSDL => tất cả dữ liệu sẽ xóa
      # create-drop: khi khởi động tạo lại CSDL khi ứng dụng và xóa schema khỏi ứng dụng => khi khởi động thì nó sẽ tạo schema table, khi tắt ứng dụng nó sẽ drop hết schema table đó
      # update: khi khởi động hibernate cập nhật schema table khớp với object trong Java được ánh xạ (không làm mất dữ liệu)
      # validate: khi khởi động hibernate đi kiểm tra xem CSDL có khớp với mô hình dữ liệu hay không? => Nó không thực hiện các thay đổi nào => Nếu có sự khác biệt thì sẽ có lỗi được báo
      # none: khi khởi động hibernate không đi tạo table (không làm gì)
      ddl-auto: update
  h2:
    console:
      enabled: true # Default true

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka